
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/author?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: aiyls
    hikari:
      maximum-pool-size: 5
  application:
    name: springboot-shiro

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      table-underline: true
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

